### PR TITLE
Added cordova iOS 4+ support

### PR DESCRIPTION
**Pull request by jcesarmobile**
Added cordova iOS 4+ support.
Moved most parts of MainViewController.m to the plugin class so the
plugin user doesn’t have to add them.
Removed the RemoteControls singleton and used the NSNotificationCenter
to pass the event to the RemoteControls class.

### CODE REVIEW

**Comment by DrakeWitt** [comment]
Pull works great! It fixed iOS 9 for me and removed the need to modify other files. I would suggest adding it to npm using the new plugin structure (like cordova-plugin-remotecontrols).

**Comment by fenta23** [comment]
Thx for working on this cordova ios4+ thing. It works again.
Currently im looking for the prev/next Buttons in control-center? How do i show them?

Thx, Micha.

**Comment by DrakeWitt** [comment]
They automatically show for me, you might have to run on a physical device. @fenta23

**Comment by shi11** [comment]
Hi @jcesarmobile - I'm sorry for my delay for trying out your PR. Can't wait to give it a go and Merge it. Thanks for picking up the ball and running with it! Can't wait.

**Comment by fenta23** [comment]
@DrakeWitt: no, they are not there... just the play/pausebutton
I would like to add listeners for those buttons, so i can skip to the next track.
img_4508

**Comment by kylesziv** [comment]
Can this be merged in?

**Comment by DrakeWitt** [comment]
This repo seams dead @kylesziv. In the mean time you can do cordova plugin add https://github.com/jcesarmobile/RemoteControls

**Comment by shi11** [comment]
It's not dead, big apologies, I'm testing this update now and will merge it this evening. I'm open to adding collaborators so that I'm not the broken the link.

**Pull request merged**
